version: "3"
services:
  erddap:
    image: axiom/docker-erddap:2.23-jdk17-openjdk
    restart: unless-stopped
    ports:
      - "80:8080"
    volumes:
      - ./erddap/conf/config.sh:/usr/local/tomcat/bin/config.sh
      - ./erddap/conf/robots.txt:/usr/local/tomcat/webapps/ROOT/robots.txt
      - ./erddap/conf/index.jsp:/usr/local/tomcat/webapps/ROOT/index.jsp
      - ./erddap/content:/usr/local/tomcat/content/erddap
      - ./erddap/data:/erddapData
      - ./datasets:/datasets

