version: "3"
services:
  fix-permissions:
    image: axiom/docker-erddap:v2.28.1
    user: "0:0"
    command:
      - /bin/bash
      - -c
      - |
        set -eux
        chmod -R a+rX /data || true
        chmod -R a+rX /erddapData/hardFlag || true
    volumes:
      - ./data:/data:z
      - ./erddapData:/erddapData:z
    restart: "no"

  erddap:
    image: axiom/docker-erddap:v2.28.1
    user: "${UID}:${GID}"
    restart: unless-stopped
    depends_on:
      - fix-permissions
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./data:/data:z
      - ./datasets.d:/datasets.d:z
      - ./erddapData:/erddapData:z
      - ./content:/usr/local/tomcat/content/erddap:z
      - ./tomcatLogs:/usr/local/tomcat/logs:z
    environment:
      #note: these can also be set in /usr/local/tomcat/bin/config.sh
      ERDDAP_MIN_MEMORY: 2G
      ERDDAP_MAX_MEMORY: 12G
      ERDDAP_bigParentDirectory: /erddapData/
      ERDDAP_baseUrl: http://erddap.nodc.se
      ERDDAP_baseHttpsUrl: http://erddap.nodc.se
      ERDDAP_flagKeyKey: change-this-value!!
      ERDDAP_emailEverythingTo:
      ERDDAP_emailDailyReportTo:
      ERDDAP_emailFromAddress:
      ERDDAP_emailUserName:
      ERDDAP_emailPassword:
      ERDDAP_emailProperties:
      ERDDAP_emailSmtpHost:
      ERDDAP_emailSmtpPort:
      ERDDAP_adminInstitution: Swedish Meteorological and Hydrological Institute
      ERDDAP_adminInstitutionUrl: https://www.nodc.se
      ERDDAP_adminIndividualName: SMHI NODC
      ERDDAP_adminPosition: Data Manager
      ERDDAP_adminPhone: "+46 (0)11 495 80 00"
      ERDDAP_adminAddress: "Göteborgseskaderns plats 3"
      ERDDAP_adminCity: Västra Frölunda
      ERDDAP_adminStateOrProvince: Västra Götalands Län
      ERDDAP_adminPostalCode: "SE-421 71"
      ERDDAP_adminCountry: Sweden
      ERDDAP_adminEmail: nodc@smhi.se
